export * from './admin.service';
import { AdminService } from './admin.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './currency.service';
import { CurrencyService } from './currency.service';
export * from './payment.service';
import { PaymentService } from './payment.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './wallet.service';
import { WalletService } from './wallet.service';
export * from './withdrawal.service';
import { WithdrawalService } from './withdrawal.service';
export const APIS = [AdminService, AuthService, CurrencyService, PaymentService, UserService, WalletService, WithdrawalService];
