/**
 * FinalStake
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { WithdrawalViewDTO } from './withdrawalViewDTO';


export interface BaseResponseWithdrawalViewDTO { 
    data?: WithdrawalViewDTO;
    error?: string;
    success?: boolean;
}

