/**
 * FinalStake
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserViewAdminDTO } from './userViewAdminDTO';


export interface BaseResponseUserViewAdminDTO { 
    data?: UserViewAdminDTO;
    error?: string;
    success?: boolean;
}

