/**
 * FinalStake
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserListViewDTO } from './userListViewDTO';


export interface BaseResponseListUserListViewDTO { 
    data?: Array<UserListViewDTO>;
    error?: string;
    success?: boolean;
}

