/**
 * FinalStake
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CheckoutSessionDTO } from './checkoutSessionDTO';


export interface BaseResponseCheckoutSessionDTO { 
    data?: CheckoutSessionDTO;
    error?: string;
    success?: boolean;
}

