/**
 * FinalStake
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserViewAdminDTO } from './userViewAdminDTO';


export interface PageResponseUserViewAdminDTO { 
    data?: Array<UserViewAdminDTO>;
    error?: string;
    pageNumber?: number;
    pageSize?: number;
    success?: boolean;
    totalElements?: number;
}

