/**
 * FinalStake
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentViewDTO } from './paymentViewDTO';


export interface PageResponsePaymentViewDTO { 
    data?: Array<PaymentViewDTO>;
    error?: string;
    pageNumber?: number;
    pageSize?: number;
    success?: boolean;
    totalElements?: number;
}

