/**
 * FinalStake
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentViewDTO { 
    amount?: number;
    completedAt?: string;
    convertedAmount?: number;
    createdAt?: string;
    currencyCode?: string;
    id?: string;
    status?: PaymentViewDTO.StatusEnum;
    username?: string;
}
export namespace PaymentViewDTO {
    export const StatusEnum = {
        Pending: 'PENDING',
        Completed: 'COMPLETED',
        Failed: 'FAILED',
        Cancelled: 'CANCELLED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


