/**
 * FinalStake
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WithdrawalViewDTO { 
    adminNote?: string;
    amount?: number;
    createdAt?: string;
    id?: string;
    payoutDetails?: string;
    payoutMethod?: string;
    processedAt?: string;
    status?: WithdrawalViewDTO.StatusEnum;
    username?: string;
}
export namespace WithdrawalViewDTO {
    export const StatusEnum = {
        Pending: 'PENDING',
        Approved: 'APPROVED',
        Rejected: 'REJECTED',
        Paid: 'PAID'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


