/**
 * FinalStake
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface WithdrawalAdminUpdateDTO { 
    adminNote?: string;
    status: WithdrawalAdminUpdateDTO.StatusEnum;
}
export namespace WithdrawalAdminUpdateDTO {
    export const StatusEnum = {
        Pending: 'PENDING',
        Approved: 'APPROVED',
        Rejected: 'REJECTED',
        Paid: 'PAID'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


