/**
 * FinalStake
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserViewDTO } from './userViewDTO';


export interface BaseResponseUserViewDTO { 
    data?: UserViewDTO;
    error?: string;
    success?: boolean;
}

