/**
 * FinalStake
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CurrencyViewDTO } from './currencyViewDTO';


export interface BaseResponseCurrencyViewDTO { 
    data?: CurrencyViewDTO;
    error?: string;
    success?: boolean;
}

